export enum PermissionType {
    // DEFAULT PERMISSIONS
    CREATE_REPORTS = 1,
    CHANGE_USERNAME = 2,

    // PLUS PERMISSIONS
    CHANGE_NAME_COLOR_TIER_1 = 3,
    CHANGE_NAME_COLOR_TIER_2 = 4,
    EARLY_ACCESS_TIER_1 = 5,
    EARLY_ACCESS_TIER_2 = 6,
    USE_CHAT_COLORS = 7,
    UPLOAD_FILES_SMALL = 8,
    UPLOAD_FILES_MEDIUM = 9,
    UPLOAD_FILES_LARGE = 10,
    CUSTOM_AVATAR = 11,
    CUSTOM_BANNER = 12,
    CHANGE_FONT = 13,
    MORE_AUCTIONS_TIER_1 = 14,
    MORE_AUCTIONS_TIER_2 = 15,
    MORE_AUCTIONS_TIER_3 = 16,
    MORE_AUCTIONS_TIER_4 = 17,
    LESS_AUCTION_TAX = 18,
    CREATE_GUILDS = 19,
    CHANGE_GUILD_COLOR = 20,
    CUSTOM_TRADING_TABLE_COLOR = 21,
    MORE_CHAT_BADGE_TIER_1 = 22,
    MORE_CHAT_BADGE_TIER_2 = 23,

    // TRIAL MODERATOR PERMISSIONS
    MUTE_USERS = 24,
    BAN_USERS = 25,
    MANAGE_MESSAGES = 26,
    VIEW_AUDIT = 27,

    // MODERATOR PERMISSIONS
    MANAGE_REPORTS = 28,

    // ADMIN PERMISSIONS
    BLACKLIST_USERS = 29,
    MANAGE_USER_PERMISSIONS = 30,
    MANAGE_USER_BLOOKS = 31,
    MANAGE_USER_ITEMS = 32,
    MANAGE_USER_TITLES = 33,
    MANAGE_USER_BANNERS = 34,
    MANAGE_USER_GROUPS = 35,
    MANAGE_NEWS_POSTS = 36,

    // CO-OWNER PERMISSIONS
    MANAGE_CHAT_ROOMS = 37,
    MANAGE_GAME_DATA = 38,
    DELETE_USERS = 39,

    // OWNER PERMISSIONS
    MANAGE_GROUPS = 40
};