export enum PermissionType {
    // DEFAULT PERMISSIONS
    CREATE_REPORTS,
    CHANGE_USERNAME,

    // PLUS PERMISSIONS
    CHANGE_NAME_COLOR_TIER_1,
    CHANGE_NAME_COLOR_TIER_2,
    EARLY_ACCESS_TIER_1,
    EARLY_ACCESS_TIER_2,
    USE_CHAT_COLORS,
    UPLOAD_FILES_SMALL,
    UPLOAD_FILES_MEDIUM,
    UPLOAD_FILES_LARGE,
    CUSTOM_AVATAR,
    CUSTOM_BANNER,
    CHANGE_FONT,
    MORE_AUCTIONS_TIER_1,
    MORE_AUCTIONS_TIER_2,
    MORE_AUCTIONS_TIER_3,
    MORE_AUCTIONS_TIER_4,
    LESS_AUCTION_TAX,
    CREATE_GUILDS,
    CHANGE_GUILD_COLOR,
    CUSTOM_TRADING_TABLE_COLOR,
    MORE_CHAT_BADGE_TIER_1,
    MORE_CHAT_BADGE_TIER_2,

    // TRIAL MODERATOR PERMISSIONS
    MUTE_USERS,
    BAN_USERS,
    MANAGE_MESSAGES,
    VIEW_AUDIT,

    // MODERATOR PERMISSIONS
    MANAGE_REPORTS,

    // ADMIN PERMISSIONS
    BLACKLIST_USERS,
    MANAGE_USER_PERMISSIONS,
    MANAGE_USER_BLOOKS,
    MANAGE_USER_ITEMS,
    MANAGE_USER_TITLES,
    MANAGE_USER_BANNERS,
    MANAGE_USER_GROUPS,
    MANAGE_NEWS_POSTS,

    // CO-OWNER PERMISSIONS
    MANAGE_CHAT_ROOMS,
    MANAGE_GAME_DATA,
    DELETE_USERS,

    // OWNER PERMISSIONS
    MANAGE_GROUPS
};