export enum AuditActionType {
    // CONSOLE
    CONSOLE_COMMAND = 1,

    // USERS
    USER_CHANGED_USERNAME = 2,
    USER_MUTED = 3,
    USER_UNMUTED = 4,
    USER_BANNED = 5,
    USER_UNBANNED = 6,
    USER_BLACKLISTED = 7,
    USER_UNBLACKLISTED = 8,
    USER_GRANTED_GROUP = 9,
    USER_REVOKED_GROUP = 10,

    // GROUPS
    GROUP_CREATE = 11,
    GROUP_UPDATE = 12,
    GROUP_DELETE = 13,

    // FORMS    
    FORM_ACCEPTED = 14,
    FORM_REJECTED = 15,

    // GUILDS
    GUILD_CREATE = 16,
    GUILD_JOINED = 17,
    GUILD_OWNERSHIP_TRANSFER = 18,
    GUILD_LEFT = 19,
    GUILD_DISBAND = 20,

    // AUCTIONS
    AUCTION_CREATE = 21,
    AUCTION_REMOVE = 22,
    AUCTION_BID = 23,

    // BOOSTERS
    BOOSTER_USE = 24
}