export enum SocketMessageType {
    UNAUTHORIZED = "UNAUTHORIZED",
    AUTHORIZED = "AUTHORIZED",

    CHAT_MESSAGES_CREATE = "CHAT_MESSAGES_CREATE",
    CHAT_TYPING_STARTED = "CHAT_TYPING_STARTED",

    AUCTIONS_EXPIRE = "AUCTIONS_EXPIRE",
    AUCTIONS_BID = "AUCTIONS_BID"
}
