export enum SocketMessageType {
    UNAUTHORIZED = "UNAUTHORIZED",
    AUTHORIZED = "AUTHORIZED",

    KEEP_ALIVE = "KEEP_ALIVE",

    CHAT_MESSAGES_CREATE = "CHAT_MESSAGES_CREATE",
    CHAT_TYPING_STARTED = "CHAT_TYPING_STARTED",

    AUCTIONS_EXPIRE = "AUCTIONS_EXPIRE",
    AUCTIONS_BID = "AUCTIONS_BID",

    TRADING_PLAZA_JOIN = "TRADING_PLAZA_JOIN",
    TRADING_PLAZA_LEAVE = "TRADING_PLAZA_LEAVE",
    TRADING_PLAZA_MOVE = "TRADING_PLAZA_MOVE"
}
